from marshmallow import Schema, fields

class CitySchema(Schema):

    id = fields.Str()
    city = fields.Str()
    currency = fields.Str()
    currencySymbol = fields.Str()
    country = fields.Str()
    state = fields.Str()
    currencyAbbr = fields.Str()
    currencyAbbrText = fields.Str()
    distanceMetrics = fields.Str()
    distanceMetricsUnit = fields.Float()
    radiusforsomeOneElseBooking = fields.Float()
    maxEtaDistanceInMeters = fields.Float()
    maxEtaTimeInSeconds = fields.Float()
    isTipEnable = fields.Boolean()
    tipType = fields.Float()
    paymentMode = fields.Dict()
    paymentGateways = fields.Dict()
    isCorporateEnable = fields.Boolean()
    isFavoriteDriverEnable = fields.Boolean()
    isDeleted = fields.Boolean()
    location = fields.Dict()
    timeOffset = fields.Str()
    polygons = fields.Dict()
    pointsProps = fields.Dict()
    dstOffset = fields.Str()
    timeZoneId = fields.Str()
    walletSettings = fields.Dict()
    isPreferenceEnabled = fields.Boolean()
    cityStatus = fields.Str()